const logoList = [
  'Tesla:Tesla.png',
  'Toyota:Toyota.png',
  'Ford:Ford.png',
  'Honda:Honda.png',
  'BMW:BMW.png',
  'Subaru:Subaru.png',
  'Hyundai:Hyundai.png',
  'Audi:Audi.png',
  'Jeep:Jeep.png',
  'Porsche:Porsche.png',
  'Dodge:Dodge.png',
  'Ferrari:Ferrari.png',
  'Jaguar:Jaguar.png',
  'Lamborghini:Lamborghini.png',
  'Maserati:Maserati.png',
  'Bentley:Bentley.png',
  'Chrysler:Chrysler.png',
  'Chevrolet Corvette:Chevrolet Corvette.png',
  'Cadillac:Cadillac.png',
  'Mazda:Mazda.png',
  'Ford Mustang:Ford Mustang.png',
  'Nissan:Nissan.png',
  'Alfa Romeo:Alfa Romeo.png',
  'Bugatti:Bugatti.png',
  'Buick:Buick.png',
  'Lexus:Lexus.png',
  'Rolls:Royce:Rolls:Royce.png',
  'Acura:Acura.png',
  'Aston Martin:Aston Martin.png',
  'Chevrolet:Chevrolet.png',
  'Kia:Kia.png',
  'Mercedes-Benz:Mercedes-Benz.png',
  'Volkswagen:Volkswagen.png',
  'Volvo:Volvo.png',
  'McLaren:McLaren.png',
  'Mitsubishi:Mitsubishi.png',
  'GMC:GMC.png',
  'Infiniti:Infiniti.png',
  'Lincoln:Lincoln.png',
  'Peugeot:Peugeot.png',
  'Pontiac:Pontiac.png',
  'Saab:Saab.png',
  'Genesis:Genesis.png',
  'Suzuki:Suzuki.png',
  'Citroën:Citroën.png',
  'Fiat:Fiat.png',
  'Lotus:Lotus.png',
  'Mini:Mini.png',
  'Peterbilt:Peterbilt.png',
  'Saturn:Saturn.png',
  'BMW M:BMW M.png',
  'General Motors:General Motors.png',
  'Kenworth:Kenworth.png',
  'KTM:KTM.png',
  'Land Rover:Land Rover.png',
  'Maybach:Maybach.png',
  'Mercury:Mercury.png',
  'Oldsmobile:Oldsmobile.png',
  'Renault:Renault.png',
  'Dodge Viper:Dodge Viper.png',
  'Koenigsegg:Koenigsegg.png',
  'Mack:Mack.png',
  'Scion:Scion.png',
  'Škoda:Škoda.png',
  'Daewoo:Daewoo.png',
  'Daimler:Daimler.png',
  'Opel:Opel.png',
  'Datsun:Datsun.png',
  'Holden:Holden.png',
  'Smart:Smart.png',
  'Alpine:Alpine.png',
  'DS:DS.png',
  'Navistar:Navistar.png',
  'Nissan Nismo:Nissan Nismo.png',
  'Pagani:Pagani.png',
  'Rover:Rover.png',
  'Vauxhall:Vauxhall.png',
  'Ariel:Ariel.png',
  'Isuzu:Isuzu.png',
  'Paccar:Paccar.png',
  'Tata:Tata.png',
  'Abarth:Abarth.png',
  'Hummer:Hummer.png',
  'SEAT:SEAT.png',
  'Karma:Karma.png',
  'Lucid:Lucid.png',
  'Saleen:Saleen.png',
  'Studebaker:Studebaker.png',
  'Western Star:Western Star.png',
  'Mercedes:AMG:Mercedes:AMG.png',
  'Hennessey:Hennessey.png',
  'Audi Sport:Audi Sport.png',
  'Dacia:Dacia.png',
  'Daihatsu:Daihatsu.png',
  'Fisker:Fisker.png',
  'Geo:Geo.png',
  'Hino:Hino.png',
  'Scania:Scania.png',
  'Sterling:Sterling.png',
  'Packard:Packard.png',
  'Great Wall:Great Wall.png',
  'Eicher:Eicher.png',
  'International:International.png',
  'IH:IH.png',
  'RAM:RAM.png',
  'ABT:ABT.png',
  'BYD:BYD.png',
  'Geely:Geely.png',
  'Lada:Lada.png',
  'Noble:Noble.png',
  'Polestar:Polestar.png',
  'MG:MG.png',
  'VinFast:VinFast.png',
  'SsangYong:SsangYong.png',
  'Alpina:Alpina.png',
  'Brabus:Brabus.png',
  'Jetta:Jetta.png',
  'MAZ:MAZ.png',
  'SAIC Motor:SAIC Motor.png',
  'MAN:MAN.png',
  'VLF:VLF.png',
  'Vencer:Vencer.png',
  'Elemental:Elemental.png',
  'Faraday Future:Faraday Future.png',
  'Rimac:Rimac.png',
  'SSC:SSC.png',
  'DeSoto:DeSoto.png',
  'GAC Group:GAC Group.png',
  'Irizar:Irizar.png',
  'Hongqi:Hongqi.png',
  'NIO:NIO.png',
  'Rivian:Rivian.png',
  'WEY:WEY.png',
  'ERF:ERF.png',
  'Spyker:Spyker.png',
  'Toyota Crown:Toyota Crown.png',
  'Suffolk:Suffolk.png',
  'De Tomaso:De Tomaso.png',
  'Freightliner:Freightliner.png',
  'IC Bus:IC Bus.png',
  'Tramontana:Tramontana.png',
  'Arash:Arash.png',
  'Artega:Artega.png',
  'Gumpert:Gumpert.png',
  'Tucker:Tucker.png',
  'Wuling:Wuling.png',
  'Sisu:Sisu.png',
  'Carlsson:Carlsson.png',
  'Troller:Troller.png',
  'Tauro Sport Auto:Tauro Sport Auto.png',
  'Tatra:Tatra.png',
  'Spania GTA:Spania GTA.png',
  'Vector:Vector.png',
  'Ascari:Ascari.png',
  'Lagonda:Lagonda.png',
  'Mansory:Mansory.png',
  'Panoz:Panoz.png',
  'Rossion:Rossion.png',
  'Canoo:Canoo.png',
  'Arrival:Arrival.png',
  'Lordstown:Lordstown.png',
  'Arrinera:Arrinera.png',
  'BharatBenz:BharatBenz.png',
  'Haval:Haval.png',
  'Mahindra:Mahindra.png',
  'Mosler:Mosler.png',
  'Trion:Trion.png',
  'Duesenberg:Duesenberg.png',
  'Changan:Changan.png',
  'Chery:Chery.png',
  'GAZ:GAZ.png',
  'Laraki:Laraki.png',
  'Perodua:Perodua.png',
  'Rezvani:Rezvani.png',
  'RUF:RUF.png',
  'TechArt:TechArt.png',
  'Brilliance:Brilliance.png',
  'David Brown:David Brown.png',
  'Hindustan Motors:Hindustan Motors.png',
  'Iveco:Iveco.png',
  'Keating:Keating.png',
  'LEVC:LEVC.png',
  'Mazzanti:Mazzanti.png',
  'TVR:TVR.png',
  'Zenvo:Zenvo.png',
  'Lynk & Co:Lynk & Co.png',
  'Toyota Century:Toyota Century.png',
  'Toyota Alphard:Toyota Alphard.png',
  'Li Auto:Li Auto.png',
  'XPeng:XPeng.png',
  'Weltmeister:Weltmeister.png',
  'Nikola:Nikola.png',
  'Workhorse:Workhorse.png',
  'Singulato:Singulato.png',
  'NEVS:NEVS.png',
  'Bestune:Bestune.png',
  'Exeed:Exeed.png',
  'Geometry:Geometry.png',
  '9ff:9ff.png',
  'Aixam:Aixam.png',
  'Apollo:Apollo.png',
  'Autobacs:Autobacs.png',
  'BAIC Motor:BAIC Motor.png',
  'Baojun:Baojun.png',
  'Bertone:Bertone.png',
  'Borgward:Borgward.png',
  'Brammo:Brammo.png',
  'Caparo:Caparo.png',
  'Caterham:Caterham.png',
  'DAF:DAF.png',
  'Devel Sixteen:Devel Sixteen.png',
  'DINA:DINA.png',
  'Dongfeng:Dongfeng.png',
  'Edsel:Edsel.png',
  'FAW:FAW.png',
  'Foton:Foton.png',
  'Ginetta:Ginetta.png',
  'Grinnall:Grinnall.png',
  'Nissan GT:R:Nissan GT:R.png',
  'HSV:HSV.png',
  'Kamaz:Kamaz.png',
  'Lancia:Lancia.png',
  'Ligier:Ligier.png',
  'Lister:Lister.png',
  'Luxgen:Luxgen.png',
  'Melkus:Melkus.png',
  'Microcar:Microcar.png',
  'Mitsuoka:Mitsuoka.png',
  'Oltcit:Oltcit.png',
  'OSCA:OSCA.png',
  'Pininfarina:Pininfarina.png',
  'Praga:Praga.png',
  'Prodrive:Prodrive.png',
  'Proton:Proton.png',
  'Qoros:Qoros.png',
  'Radical:Radical.png',
  'Renault Samsung:Renault Samsung.png',
  'Setra:Setra.png',
  'UAZ:UAZ.png',
  'UD:UD.png',
  'W Motors:W Motors.png',
  'Yulon:Yulon.png',
  'Zarooq Motors:Zarooq Motors.png',
  'Zenos:Zenos.png',
  'Stutz:Stutz.png',
  'Karlmann King:Karlmann King.png',
  'Byton:Byton.png',
  'FSO:FSO.png',
  'Drako Motors:Drako Motors.png',
  'Aspark:Aspark.png',
  'FAW Jiefang:FAW Jiefang.png',
  'Sinotruk (CNHTC):Sinotruk (CNHTC).png',
  'Shacman:Shacman.png',
  'Hongyan:Hongyan.png',
  'Dayun:Dayun.png',
  'BeiBen:BeiBen.png',
  'CAMC:CAMC.png',
  'Yutong:Yutong.png',
  'King Long:King Long.png',
  'Golden Dragon:Golden Dragon.png',
  'Zhongtong:Zhongtong.png',
  'Higer:Higer.png',
  'Zinoro:Zinoro.png',
  'HiPhi:HiPhi.png',
  'Leapmotor:Leapmotor.png',
  'Zeekr:Zeekr.png',
  'Aiways:Aiways.png',
  'AC:AC.png',
  'Alvis:Alvis.png',
  'Atalanta:Atalanta.png',
  'BAC:BAC.png',
  'Bitter:Bitter.png',
  'Bowler:Bowler.png',
  'Bufori:Bufori.png',
  'Changfeng:Changfeng.png',
  'Dartz:Dartz.png',
  'Detroit Electric:Detroit Electric.png',
  'DeLorean:DeLorean.png',
  'Donkervoort:Donkervoort.png',
  'Eagle:Eagle.png',
  'EDAG:EDAG.png',
  'Elfin:Elfin.png',
  'Eterniti:Eterniti.png',
  'Facel Vega:Facel Vega.png',
  'Force:Force.png',
  'FPV:FPV.png',
  'Haima:Haima.png',
  'Hawtai:Hawtai.png',
  'IKCO:IKCO.png',
  'JAC:JAC.png',
  'Jawa:Jawa.png',
  'JBA Motors:JBA Motors.png',
  'JMC:JMC.png',
  'Landwind:Landwind.png',
  'Lifan:Lifan.png',
  'Lloyd:Lloyd.png',
  'Lobini:Lobini.png',
  'Maxus:Maxus.png',
  'Morgan:Morgan.png',
  'Roewe:Roewe.png',
  'Spirra:Spirra.png',
  'Venucia:Venucia.png',
  'Westfield:Westfield.png',
  'Wiesmann:Wiesmann.png',
  'Abadal:Abadal.png',
  'Abbott:Detroit:Abbott:Detroit.png',
  'Alta:Alta.png',
  'AMC:AMC.png',
  'ARO:ARO.png',
  'Askam:Askam.png',
  'Auburn:Auburn.png',
  'Austin:Austin.png',
  'Autobianchi:Autobianchi.png',
  'Axon:Axon.png',
  'Berkeley:Berkeley.png',
  'Berliet:Berliet.png',
  'Bizzarrini:Bizzarrini.png',
  'Bristol:Bristol.png',
  'Brooke:Brooke.png',
  'Cisitalia:Cisitalia.png',
  'Cizeta:Cizeta.png',
  'Cole:Cole.png',
  'Corre La Licorne:Corre La Licorne.png',
  'Delage:Delage.png',
  'Diatto:Diatto.png',
  'DKW:DKW.png',
  'Elva:Elva.png',
  'Englon:Englon.png',
  'Fioravanti:Fioravanti.png',
  'Foden:Foden.png',
  'Franklin:Franklin.png',
  'Gardner Douglas:Gardner Douglas.png',
  'Gilbern:Gilbern.png',
  'Gillet:Gillet.png',
  'Gonow:Gonow.png',
  'Hillman:Hillman.png',
  'Hispano:Suiza:Hispano:Suiza.png',
  'Hommell:Hommell.png',
  'Horch:Horch.png',
  'Hudson:Hudson.png',
  'Hupmobile:Hupmobile.png',
  'Innocenti:Innocenti.png',
  'Intermeccanica:Intermeccanica.png',
  'Isdera:Isdera.png',
  'Iso:Iso.png',
  'Jensen:Jensen.png',
  'Kaiser:Kaiser.png',
  'Leyland:Leyland.png',
  'Marcos:Marcos.png',
  'Marlin:Marlin.png',
  'Mastretta:Mastretta.png',
  'Merkur:Merkur.png',
  'MEV:MEV.png',
  'MK:MK.png',
  'Morris:Morris.png',
  'Panhard:Panhard.png',
  'Pegaso:Pegaso.png',
  'PGO:PGO.png',
  'Pierce:Arrow:Pierce:Arrow.png',
  'Plymouth:Plymouth.png',
  'Premier:Premier.png',
  'Rambler:Rambler.png',
  'Riley:Riley.png',
  'Rinspeed:Rinspeed.png',
  'Ronart:Ronart.png',
  'Saipa:Saipa.png',
  'Simca:Simca.png',
  'Singer:Singer.png',
  'Soueast:Soueast.png',
  'Talbot:Talbot.png',
  'Triumph:Triumph.png',
  'Ultima:Ultima.png',
  'Vandenbrink:Vandenbrink.png',
  'Venturi:Venturi.png',
  'Wanderer:Wanderer.png',
  'Wartburg:Wartburg.png',
  'Willys:Overland:Willys:Overland.png',
  'Zastava:Zastava.png',
  'ZAZ:ZAZ.png',
  'Zotye:Zotye.png',
  'Hafei:Hafei.png',
  'Ranz:Ranz.png',
];

module.exports = logoList;
